# Generated by Django 4.1.5 on 2023-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_content_test_text_testvar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='text',
            new_name='content',
        ),
    ]
