# Generated by Django 4.1.5 on 2023-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_text_test_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvar',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
