# Generated by Django 4.1.5 on 2023-01-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_testvar_options_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Theme',
        ),
    ]
