# Generated by Django 4.1.5 on 2023-02-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_lesson_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lesson',
            new_name='theme',
        ),
    ]
