# Generated by Django 4.1.5 on 2023-02-11 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_lesson_task_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
