# Generated by Django 4.1.5 on 2023-02-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_quizmultiplechoice_remove_lecture_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Quiz',
        ),
        migrations.RenameModel(
            old_name='TestVar',
            new_name='QuizVar',
        ),
    ]
